### ISSUE TITLE
张志伟是大傻子

### ISSUE THREAD

**Issue by Astar567** [wulebuzuo-hash/A-interesting-team#1]

**Comment by Astar567** [comment]
？？

**Comment by wulebuzuo-hash** [comment]
张宇是个畜牲




------------------ 原始邮件 ------------------
发件人: "Astar567"<notifications@github.com>;
发送时间: 2019年10月13日(星期天) 中午12:02
收件人: "wulebuzuo-hash/A-interesting-team"<A-interesting-team@noreply.github.com>;
抄送: "轻语岁月，淡看流年"<2233484461@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [wulebuzuo-hash/A-interesting-team] 张志伟是大傻子 (#1)




？？

**Comment by Astar567** [comment]
傻了？？ 张志伟傻子------------------ 原始邮件 ------------------
发件人: "wulebuzuo-hash"<notifications@github.com>
发送时间: 2019年10月14日(星期一) 晚上6:13
收件人: "wulebuzuo-hash/A-interesting-team"<A-interesting-team@noreply.github.com>;
抄送: "Astar567"<2056146837@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wulebuzuo-hash/A-interesting-team] 张志伟是大傻子 (#1)


张宇是个畜牲 
 
 
 
 
 ------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人: "Astar567"<notifications@github.com>; 
 发送时间: 2019年10月13日(星期天) 中午12:02 
 收&#x4EF6;人: "wulebuzuo-hash/A-interesting-team"<A-interesting-team@noreply.github.com>; 
 抄送: "轻语岁月，淡看流年"<2233484461@qq.com>;"State change"<state_change@noreply.github.com>; 
 主题: Re: [wulebuzuo-hash/A-interesting-team] 张志伟是大傻子 (#1) 
 
 
 
 
 ？？ 
   
 — 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;
